CREATE TABLE flights_schedule (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    flight_number VARCHAR(10) NOT NULL UNIQUE ,
    departure_airport VARCHAR(50) NOT NULL ,
    arrival_airport VARCHAR(50) NOT NULL ,
    departure_time TIMESTAMP NOT NULL ,
    arrival_time TIMESTAMP NOT NULL ,
    aircraft_id INTEGER NOT NULL ,
    PRIMARY KEY (id),
    FOREIGN KEY (aircraft_id) REFERENCES fleets (id)
);