CREATE TABLE user_details (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    first_name VARCHAR(50) NOT NULL ,
    second_name VARCHAR(50) NOT NULL ,
    patronymic VARCHAR(50) ,
    document_number VARCHAR(10) NOT NULL ,
    user_id BIGINT NOT NULL ,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);