CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    seat_number VARCHAR(5) NOT NULL,
    is_reserved BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (flight_id) REFERENCES flights_schedule(id)
);