CREATE TABLE bookings (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    user_id BIGINT NOT NULL ,
    user_details BIGINT NOT NULL ,
    flight_id BIGINT NOT NULL ,
    seat VARCHAR(5) NOT NULL ,
    status VARCHAR(20) NOT NULL ,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (user_details) REFERENCES user_details (id),
    FOREIGN KEY (flight_id) REFERENCES flights_schedule (id)
);